import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { PortuguesPuroGeneratedModule, PortuguesPuroGeneratedSharedModule } from './generated/module.js';
import { PortuguesPuroValidator, registerValidationChecks } from './pop-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type PortuguesPuroAddedServices = {
    validation: {
        PortuguesPuroValidator: PortuguesPuroValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type PortuguesPuroServices = LangiumServices & PortuguesPuroAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const PortuguesPuroModule: Module<PortuguesPuroServices, PartialLangiumServices & PortuguesPuroAddedServices> = {
    validation: {
        PortuguesPuroValidator: () => new PortuguesPuroValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createPortuguesPuroServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    PortuguesPuro: PortuguesPuroServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        PortuguesPuroGeneratedSharedModule
    );
    const PortuguesPuro = inject(
        createDefaultModule({ shared }),
        PortuguesPuroGeneratedModule,
        PortuguesPuroModule
    );
    shared.ServiceRegistry.register(PortuguesPuro);
    registerValidationChecks(PortuguesPuro);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, PortuguesPuro };
}
